### PR TITLE
Add a button to export HTML

### PR DESCRIPTION
**Pull request by firtoz**
Using the already existing `PreviewModal` component for it :D 

https://github.com/tldraw/draw-a-ui/assets/108406948/c7cb1146-e022-47dd-88e2-c41f2ee03693

### CODE REVIEW

**Comment by firtoz** [comment]
@steveruizok hi, I updated the PR :) Please let me know if you're not interested in PRs to the repo, I love the project and am happy to add to it, but I understand if it's not a project that cares for external contributors for example.

**Comment by steveruizok** [comment]
Hey, things are super hot and chaotic at the moment! I did add a "copy" button that will copy the html, is that useful?

**Comment by firtoz** [comment]
> Hey, things are super hot and chaotic at the moment!

Haha, can totally imagine! I wish for the best! 

>  I did add a "copy" button that will copy the html, is that useful?

If it allows us to copy html, all good indeed :)

**Comment by firtoz** [comment]
> Hey, things are super hot and chaotic at the moment! 

Can imagine!

> I did add a "copy" button that will copy the html, is that useful?

That sounds good, cheers!

**Pull request closed without merging**
